language: node_js
node_js: 
  - 8
cache:
  directories:
  - node modules
script: 
  - npm build
  - npm test -- --coverage && cat ./coverage/lcov.info | coveralls 
deploy:
  provier: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local-dir: build
  on:
    branch: master

